name: sanmill
description: Sanmill is a open-source, powerful Nine Men's Morris (and its variants) program.

version: 1.0.5+1819

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  soundpool: ^2.0.0-nullsafety.0
  path_provider: ^2.0.1
  package_info_plus: ^1.0.1
  uuid: ^3.0.4
  url_launcher: ^6.0.3
  intl: 0.17.0
  animated_text_kit: ^4.1.1
  flutter_colorpicker: ^0.4.0
  catcher: ^0.6.6
  stack_trace: ^1.10.0
  device_info_plus_platform_interface: ^1.0.1
  devicelocale: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^2.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/licenses/GPL-3.0.txt
    - assets/audios/draw.mp3
    - assets/audios/fly.mp3
    - assets/audios/go.mp3
    - assets/audios/illegal.mp3
    - assets/audios/lose.mp3
    - assets/audios/mill.mp3
    - assets/audios/place.mp3
    - assets/audios/remove.mp3
    - assets/audios/select.mp3
    - assets/audios/win.mp3

flutter_intl:
  enabled: true

msix_config:
  display_name: Mill (N Men's Morris)
  publisher_display_name: Calcitem Studio
  identity_name: 25314CalcitemStudio.Sanmill
  msix_version: 1.0.5.0
  certificate_path: sanmill.pfx
  certificate_password: secret
  publisher: CN=3413C020-B420-4E0A-8687-A2C35E878F3A
  logo_path: android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  start_menu_icon_path: android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  tile_icon_path: android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  languages: en-us, zh-cn
  capabilities: ''
  store: false

