name: sanmill
description: Sanmill is a open-source, powerful UCI-like Nine Men's Morris (and its variants) program.

version: 1.0.4+1776

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  soundpool: ^2.0.0-nullsafety.0
  path_provider: ^2.0.1
  package_info_plus: ^1.0.1
  uuid: ^3.0.4
  url_launcher: ^6.0.3
  intl: 0.17.0
  animated_text_kit: ^4.1.1
  flutter_colorpicker: ^0.4.0
  catcher: ^0.6.6
  stack_trace: ^1.10.0
  device_info_plus_platform_interface: ^1.0.1
  devicelocale: ^0.4.1
  msix: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/licenses/GPL-3.0.txt
    - assets/audios/draw.mp3
    - assets/audios/fly.mp3
    - assets/audios/go.mp3
    - assets/audios/illegal.mp3
    - assets/audios/lose.mp3
    - assets/audios/mill.mp3
    - assets/audios/place.mp3
    - assets/audios/remove.mp3
    - assets/audios/select.mp3
    - assets/audios/win.mp3

flutter_intl:
  enabled: true

msix:
  store: true
