name: Flutter

on:
  push:
    branches: [ windows ]
  pull_request:
    branches: [ windows ]

jobs:
  build:
    runs-on: windows-latest

    # Note that this workflow uses the latest stable version of the Dart SDK.
    # Docker images for other release channels - like dev and beta - are also
    # available. See https://hub.docker.com/r/google/dart/ for the available
    # images.
    #container:
    #  image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'dev' or 'beta'

      - name: Create App version
        run: git fetch --tags; git tag; git log -n1; bash -x ./version.sh

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: cd src/ui/flutter_app; flutter pub get; flutter pub global activate intl_utils; flutter --no-color pub global run intl_utils:generate

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      #- name: Run tests
      #  run: dart test

      # Build
      - name: Build Windows
        run: cd src/ui/flutter_app; flutter config --enable-windows-desktop; flutter build windows; flutter pub run msix:create --store

      # Archive msix
      - name: Archive msix
        uses: actions/upload-artifact@v2
        with:
          name: sanmill-flutter-msix-release
          path: src/ui/flutter_app/build/windows/runner/Release/sanmill.msix
